traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8088:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

intervention:
  image: teamdronefireman/intervention-service
  container_name: intervention-service
  ports:
    - "12345:3000"
  labels:
    - "traefik.backend=intervention"
    - "traefik.frontend.rule=Host:intervention.docker.localhost"

user:
  image: teamdronefireman/user-service
  container_name: user-service
  ports:
    - "12346:3000"
  labels:
    - "traefik.backend=user"
    - "traefik.frontend.rule=Host:user.docker.localhost"

mean:
  image: teamdronefireman/mean-service
  container_name: mean-service
  ports:
    - "12347:3000"
  labels:
    - "traefik.backend=mean"
    - "traefik.frontend.rule=Host:mean.docker.localhost"

sinister:
  image: teamdronefireman/sinister-service
  container_name: sinister-service
  ports:
    - "12348:3000"
  labels:
    - "traefik.backend=sinister"
    - "traefik.frontend.rule=Host:sinister.docker.localhost"

drone:
  image: teamdronefireman/drone-service
  container_name: drone-service
  ports:
    - "12349:3000"
  labels:
    - "traefik.backend=drone"
    - "traefik.frontend.rule=Host:drone.docker.localhost"

sig:
  image: teamdronefireman/sig-service
  container_name: sig-service
  ports:
    - "12350:3000"
  labels:
    - "traefik.backend=sig"
    - "traefik.frontend.rule=Host:sig.docker.localhost"
