traefik:
  image: traefik
  container_name: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8088:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

user:
  image: teamdronefireman/user-service
  container_name: user-service
  ports:
    - "12346:3000"
  labels:
    - "traefik.backend=user"
    - "traefik.frontend.rule=Host:user.docker.localhost"
  links:
    - mongo-prod:mongo
  environment:
    - NODE_ENV=PROD

intervention:
  image: teamdronefireman/intervention-service
  container_name: intervention-service
  ports:
    - "12345:3000"
  labels:
    - "traefik.backend=intervention"
    - "traefik.frontend.rule=Host:intervention.docker.localhost"
  links:
    - mongo-prod:mongo
  environment:
    - NODE_ENV=PROD
  volumes:
    - /root/teamdronefireman/gcm:/root/teamdronefireman/gcm

mean:
  image: teamdronefireman/mean-service
  container_name: mean-service
  ports:
    - "12347:3000"
  labels:
    - "traefik.backend=mean"
    - "traefik.frontend.rule=Host:mean.docker.localhost"
  links:
    - mongo-prod:mongo
  environment:
    - NODE_ENV=PROD

drone:
  image: teamdronefireman/drone-service
  container_name: drone-service
  ports:
    - "12349:3000"
  labels:
    - "traefik.backend=drone"
    - "traefik.frontend.rule=Host:drone.docker.localhost"
  links:
    - mongo-prod:mongo
  environment:
    - NODE_ENV=PROD

sig:
  image: teamdronefireman/sig-service
  container_name: sig-service
  ports:
    - "12350:3000"
  labels:
    - "traefik.backend=sig"
    - "traefik.frontend.rule=Host:sig.docker.localhost"
  links:
    - mongo-prod:mongo
  environment:
    - NODE_ENV=PROD

image:
  image: teamdronefireman/image-service
  container_name: image-service
  ports:
    - "12353:3000"
  labels:
    - "traefik.backend=image"
    - "traefik.frontend.rule=Host:image.docker.localhost"
  links:
    - mongo-prod:mongo
  environment:
    - NODE_ENV=PROD

sinister:
  image: teamdronefireman/sinister-service
  container_name: sinister-service
  ports:
    - "12348:3000"
  labels:
    - "traefik.backend=sinister"
    - "traefik.frontend.rule=Host:sinister.docker.localhost"
  links:
    - mongo-prod:mongo
  environment:
    - NODE_ENV=PROD

sig-extern:
  image: teamdronefireman/sig-extern-service
  container_name: sig-extern-service
  ports:
    - "12352:3000"
  labels:
    - "traefik.backend=sig-extern"
    - "traefik.frontend.rule=Host:sig-extern.docker.localhost"
  links:
    - mongo-prod:mongo
  environment:
    - NODE_ENV=PROD

mongo-prod:
  image: mongo
  container_name: mongo-prod
  ports:
    - "27017:27017"
  volumes_from:
    - mongo-prod-data-volume
